version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb # The name of the service
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    restart: always # In case of crash, we have to restart
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql # The folder for the MYSQL
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html # The volume folder for the web
    env_file:
      - .env

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443" # NGINX entryopint is only 443
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html # NGINX have to access the files to serve the site
    env_file:
      - .env

# Configuration to start
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/miafonso/data/wordpress
      o: bind

  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/miafonso/data/mariadb
      o: bind

networks:
  inception:
    driver: bridge